application: hotot-extend
version: 4
api_version: 1
runtime: python27
threadsafe: no

libraries:
- name: jinja2
  version: latest

handlers:
- url: /css
  static_dir: css

- url: /image
  static_dir: image

- url: /create.json
  script: create.py

- url: /tweet/.*
  script: get.py
  
- url: /.*
  script: show.py
  
